#ifndef __IFAUTHSERVICE_METHOD_ID_H__
#define __IFAUTHSERVICE_METHOD_ID_H__
#include "../../../ServiceTemplate/include/ServiceIdDef.h"

#define IFAUTHSERVICE_INTERFACE_ID ((0x00000000) * 200) 
#define IfAuthServiceServiceId (AUTHENTICATE_SERVICE_SERVICE_ID*1000)
#define IfAuthServiceServiceIdBegin AUTHENTICATE_TUINT32_TCHAR_PT_TCHAR_PT_ID
#define AUTHENTICATE_TUINT32_TCHAR_PT_TCHAR_PT_ID ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHSERVICE_INTERFACE_ID+(0))
#define ONDISCONNETED_CDOID_ID ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHSERVICE_INTERFACE_ID+(1))
#define IfAuthServiceServiceIdEnd ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHSERVICE_INTERFACE_ID+(0x00000002))
#endif

