#ifndef __IFAUTHRESP_METHOD_ID_H__
#define __IFAUTHRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFAUTHRESP_INTERFACE_ID ((0x00000001) * 200) 
#define IfAuthRespServiceId (IfAuthRespServiceIdBegin)
#define IfAuthRespServiceIdBegin RESPAUTHENTICATE_TINT32_TUINT64_ID
#define RESPAUTHENTICATE_TINT32_TUINT64_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(0))
#define CONFIRMDISCONNETED_CDOID_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(1))
#define IfAuthRespServiceIdEnd ((AUTHENTICATE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(0x00000002))
#endif

