#ifndef __IFAUTHRESP_METHOD_ID_H__
#define __IFAUTHRESP_METHOD_ID_H__
#include "../../../ServiceTemplate/include/ServiceIdDef.h"

#define IFAUTHRESP_INTERFACE_ID ((0x00000001) * 200) 
#define IfAuthRespServiceId (AUTHENTICATE_SERVICE_SERVICE_ID*1000)
#define IfAuthRespServiceIdBegin RESPAUTHENTICATE_TINT32_ID
#define RESPAUTHENTICATE_TINT32_ID ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(0))
#define CONFIRMDISCONNETED_CDOID_ID ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(1))
#define IfAuthRespServiceIdEnd ((AUTHENTICATE_SERVICE_SERVICE_ID*1000)+IFAUTHRESP_INTERFACE_ID+(0x00000002))
#endif

