#ifndef __IFUSERSESSION_METHOD_ID_H__
#define __IFUSERSESSION_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFUSERSESSION_INTERFACE_ID ((0x00000002) * 200) 
#define IfUserSessionServiceId (IfUserSessionServiceIdBegin)
#define IfUserSessionServiceIdBegin CHANGEPWD_TCHAR_PT_TCHAR_PT_ID
#define CHANGEPWD_TCHAR_PT_TCHAR_PT_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(0))
#define REQGETMYINFO_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(1))
#define REQGETUSERINFO_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(2))
#define REQGETDEPARTMENTINFO_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(3))
#define REQGETMENUINFOLIST_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(4))
#define REQUPDATEMENUINFO_TJOBINFOS_REF_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(5))
#define REQGETACTIVEWORKINFO_TINT32_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(6))
#define REQGETMYWORKLIST_TUINT32_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(7))
#define REQGETMENUINFOBYID_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(8))
#define IfUserSessionServiceIdEnd ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSION_INTERFACE_ID+(0x00000009))
#endif

