#ifndef __IFUSERSESSIONRESP_METHOD_ID_H__
#define __IFUSERSESSIONRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFUSERSESSIONRESP_INTERFACE_ID ((0x00000003) * 200) 
#define IfUsersessionRespServiceId (IfUsersessionRespServiceIdBegin)
#define IfUsersessionRespServiceIdBegin ONPWDCHANGED_TINT32_ID
#define ONPWDCHANGED_TINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(0))
#define RESPGETMYINFO_TUINT32_TCHAR_PT_TCHAR_PT_TUINT32_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(1))
#define RESPGETUSERINFO_TUINT32_TCHAR_PT_TCHAR_PT_TUINT32_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(2))
#define RESPGETDEPARTINFO_TUINT32_TCHAR_PT_TUINT32_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(3))
#define SENDJOBLIST_LIST_TPL_BEGIN_TJOBINFOS_TPL_END__REF_LIST_TPL_BEGIN_TJOBINFOS_TPL_END__REF_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(4))
#define SENDACTIVEWORK_TJOBINFOS_TUINT32_CONST_TCHAR_PT_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(5))
#define RESPMENULIST_LIST_TPL_BEGIN_TJOBINFOS_TPL_END__ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(6))
#define RESPGETMENUINFO_TJOBINFOS_REF_ID ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(7))
#define IfUsersessionRespServiceIdEnd ((AUTHENTICATE_SERVICE_ID*1000)+IFUSERSESSIONRESP_INTERFACE_ID+(0x00000008))
#endif

