#ifndef __IFLOGICRESP_METHOD_ID_H__
#define __IFLOGICRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFLOGICRESP_INTERFACE_ID ((0x00000003) * 200) 
#define RESPTEST_TINT32_ID ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICRESP_INTERFACE_ID+(0))
#define IFLOGICRESP_INTERFACE_ID_END (IFLOGICRESP_INTERFACE_ID+(Ox00000001)
#endif

