#ifndef __IFLOGICRESP_METHOD_ID_H__
#define __IFLOGICRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFLOGICRESP_INTERFACE_ID ((0x00000003) * 200) 
#define IfLogicRespServiceId (TEST_LOGIC_SERVICE_ID*1000)
#define IfLogicRespServiceIdBegin RESPTEST_TINT32_ID
#define RESPTEST_TINT32_ID ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICRESP_INTERFACE_ID+(0))
#define IfLogicRespServiceIdEnd ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICRESP_INTERFACE_ID+(0x00000001))
#endif

