#ifndef __IFLOGICSERVICE_METHOD_ID_H__
#define __IFLOGICSERVICE_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFLOGICSERVICE_INTERFACE_ID ((0x00000000) * 200) 
#define IfLogicServiceServiceId (TEST_LOGIC_SERVICE_ID*1000)
#define IfLogicServiceServiceIdBegin REQGETSESSION_TUINT64_CDOID_OCTSEQ_TPL_BEGIN_TUINT16_TPL_END__ID
#define REQGETSESSION_TUINT64_CDOID_OCTSEQ_TPL_BEGIN_TUINT16_TPL_END__ID ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICSERVICE_INTERFACE_ID+(0))
#define REQRELEASESESSION_TUINT64_CDOID_OCTSEQ_TPL_BEGIN_TUINT16_TPL_END__ID ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICSERVICE_INTERFACE_ID+(1))
#define IfLogicServiceServiceIdEnd ((TEST_LOGIC_SERVICE_ID*1000)+IFLOGICSERVICE_INTERFACE_ID+(0x00000002))
#endif

