#ifndef __IFCONNECTING_METHOD_ID_H__
#define __IFCONNECTING_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFCONNECTING_INTERFACE_ID ((0x00000002) * 200) 
#define IfConnectingServiceId (GATEWAY_SERVICE_ID*1000)
#define IfConnectingServiceIdBegin REGISTERSERVICE_CDOID_PT_TUINT32_TUINT32_TUINT32_TUINT32_ID
#define REGISTERSERVICE_CDOID_PT_TUINT32_TUINT32_TUINT32_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(0))
#define UNREGISTERSERVICE_TUINT32_TUINT32_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(1))
#define REGISTERTEAM_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(2))
#define DISCONNECT_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(3))
#define SETID_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(4))
#define CHECKID_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(5))
#define SENDCRYPTEDKEY_OCTSEQ_TPL_BEGIN_TUINT32_TPL_END__TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(6))
#define IfConnectingServiceIdEnd ((GATEWAY_SERVICE_ID*1000)+IFCONNECTING_INTERFACE_ID+(0x00000007))
#endif

