#ifndef __IFGATEWAYRESP_METHOD_ID_H__
#define __IFGATEWAYRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFGATEWAYRESP_INTERFACE_ID ((0x00000001) * 200) 
#define IfGatewayRespServiceId (GATEWAY_SERVICE_ID*1000)
#define IfGatewayRespServiceIdBegin CONFIRMREGISTERSERVICE_TUINT32_ID
#define CONFIRMREGISTERSERVICE_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYRESP_INTERFACE_ID+(0))
#define CONFIRMUNREGISTERSERVICE_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYRESP_INTERFACE_ID+(1))
#define IfGatewayRespServiceIdEnd ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYRESP_INTERFACE_ID+(0x00000002))
#endif

