#ifndef __IFGATEWAYSVC_METHOD_ID_H__
#define __IFGATEWAYSVC_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFGATEWAYSVC_INTERFACE_ID ((0x00000000) * 200) 
#define IfGatewaySvcServiceId (GATEWAY_SERVICE_ID*1000)
#define IfGatewaySvcServiceIdBegin SYN2MAP_TUINT32_TLV_TPL_BEGIN_TUINT8_AND_TUINT16_TPL_END__REF_ID
#define SYN2MAP_TUINT32_TLV_TPL_BEGIN_TUINT8_AND_TUINT16_TPL_END__REF_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(0))
#define REGISTERSERVICE_TUINT32_TUINT32_TUINT32_TUINT32_OCTSEQ_TPL_BEGIN_TUINT16_TPL_END__REF_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(1))
#define UNREGISTERSERVICE_TUINT32_TUINT32_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(2))
#define BROADCASTTEAMMSG_TUINT32_OCTSEQ_TPL_BEGIN_TUINT16_TPL_END__REF_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(3))
#define CHANGEPRIORTY_TUINT32_CDOID_PT_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(4))
#define STARTLOGIN_TUINT32_TUINT16_TUINT16_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(5))
#define STOPLOGIN_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(6))
#define DISCONNECTEDALLCLIENT_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(7))
#define IfGatewaySvcServiceIdEnd ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYSVC_INTERFACE_ID+(0x00000008))
#endif

