#ifndef __IFGATEWAYRESP_METHOD_ID_H__
#define __IFGATEWAYRESP_METHOD_ID_H__
#include "../../include/ServiceIdDef.h"

#define IFGATEWAYRESP_INTERFACE_ID ((0x00000001) * 200) 
#define CONFIRMREGISTERSERVICE_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYRESP_INTERFACE_ID+(0))
#define CONFIRMUNREGISTERSERVICE_TUINT32_ID ((GATEWAY_SERVICE_ID*1000)+IFGATEWAYRESP_INTERFACE_ID+(1))
#define IFGATEWAYRESP_INTERFACE_ID_END (IFGATEWAYRESP_INTERFACE_ID+(Ox00000002)
#endif

